# Generated by Django 4.2.4 on 2023-08-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="destination_city",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="flight",
            name="source_city",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
